- name: Скачивание файла
  ansible.builtin.get_url:
    url: "{{ roles_alloy_url }}"
    dest: /tmp/alloy-linux-amd64
  delegate_to: localhost
  run_once: true

- name: Передача файла
  ansible.builtin.copy:
    src: /tmp/alloy-linux-amd64
    dest: /usr/local/bin/alloy
    mode: '0755'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Настройка systemd сервиса
  ansible.builtin.copy:
    src: alloy.service
    dest: /etc/systemd/system/alloy.service

- name: Подготовка директории
  ansible.builtin.file:
    path: /etc/alloy
    state: directory

- name: Передача конфига
  ansible.builtin.copy:
    src: config.alloy
    dest: /etc/alloy/config.alloy

- name: Cчитывание новых сервисов
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Активация сервиса
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: alloy
